### ISSUE TITLE
“unexpected keyword argument 'max_seq_len'” in model initialization in train.py

### ISSUE THREAD

**Issue by BruceLeeeee** [Alpha-VLLM/Lumina-T2X#10]
TypeError: DiT_Llama.__init__() got an unexpected keyword argument 'max_seq_len'

**Comment by PommesPeter** [comment]
Hi Bruce,

Could you give more error messages when you are using our code? @BruceLeeeee

**Comment by BruceLeeeee** [comment]
Hi, @PommesPeter 
I tried to finetune the model, but no matter how I set it up the image size or batch size or precision (I remove the 'max_seq_len' argument), I got an CUDA out of memory error. I tried on single 80G A100.

**Comment by Frankluox** [comment]
> Hi, @PommesPeter I tried to finetune the model, but no matter how I set it up the image size or batch size or precision (I remove the 'max_seq_len' argument), I got an CUDA out of memory error. I tried on single 80G A100.

We are checking the training/tuning code and since China is on holiday now, we will fix all bugs after the holiday.

**Comment by PommesPeter** [comment]
> Hi, @PommesPeter I tried to finetune the model, but no matter how I set it up the image size or batch size or precision (I remove the 'max_seq_len' argument), I got an CUDA out of memory error. I tried on single 80G A100.

Could you give more error information (e.g. error traceback, etc.), we will fix the problems.

**Comment by BruceLeeeee** [comment]
`Traceback (most recent call last):
  File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/train.py", line 753, in <module>
    main(args)
  File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/train.py", line 514, in main
    loss_dict = transport.training_losses(model, x_mb, model_kwargs)
  File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/transport/transport.py", line 148, in training_losses
    model_output = model(xt, t, **model_kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 839, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/models/model.py", line 751, in forward
    x = layer(
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 839, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/models/model.py", line 555, in forward
    modulate(self.ffn_norm(x), shift_mlp, scale_mlp),
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/models/components.py", line 53, in forward
    output = self._norm(x.float()).type_as(x)
  File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/models/components.py", line 40, in _norm
    return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + self.eps)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB. GPU 0 has a total capacty of 79.35 GiB of which 32.19 MiB is free. Process 30630 has 79.31 GiB memory in use. Of the allocated memory 76.58 GiB is allocated by PyTorch, and 848.92 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

`# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   2.1.0                    pypi_0    pypi
accelerate                0.30.0                   pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
altair                    5.3.0                    pypi_0    pypi
annotated-types           0.6.0                    pypi_0    pypi
anyio                     4.3.0                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
boto3                     1.34.98                  pypi_0    pypi
botocore                  1.34.98                  pypi_0    pypi
bzip2                     1.0.8                h5eee18b_6  
ca-certificates           2024.3.11            h06a4308_0  
certifi                   2022.12.7                pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
cstl                      0.0.5                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
diffusers                 0.27.2                   pypi_0    pypi
dnspython                 2.6.1                    pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
email-validator           2.1.1                    pypi_0    pypi
esdk-obs-python           3.24.3                   pypi_0    pypi
exceptiongroup            1.2.1                    pypi_0    pypi
fairscale                 0.4.13                   pypi_0    pypi
fastapi                   0.111.0                  pypi_0    pypi
fastapi-cli               0.0.2                    pypi_0    pypi
ffmpy                     0.3.2                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
flash-attn                2.3.1.post1              pypi_0    pypi
fonttools                 4.51.0                   pypi_0    pypi
fsspec                    2024.2.0                 pypi_0    pypi
gradio                    4.29.0                   pypi_0    pypi
gradio-client             0.16.1                   pypi_0    pypi
grpcio                    1.63.0                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
h5py                      3.11.0                   pypi_0    pypi
httpcore                  1.0.5                    pypi_0    pypi
httptools                 0.6.1                    pypi_0    pypi
httpx                     0.27.0                   pypi_0    pypi
huggingface-hub           0.23.0                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        7.1.0                    pypi_0    pypi
importlib-resources       6.4.0                    pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jsonschema                4.22.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
markdown                  3.6                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.8.4                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  3.2.1                    pypi_0    pypi
ninja                     1.11.1.1                 pypi_0    pypi
numpy                     1.26.3                   pypi_0    pypi
opencv-python             4.9.0.80                 pypi_0    pypi
openssl                   3.0.13               h7f8727e_1  
orjson                    3.10.3                   pypi_0    pypi
packaging                 24.0                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       23.3.1                   pypi_0    pypi
protobuf                  5.26.1                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
pycryptodome              3.20.0                   pypi_0    pypi
pydantic                  2.7.1                    pypi_0    pypi
pydantic-core             2.18.2                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
python                    3.10.14              h955ad1f_0  
python-dateutil           2.9.0.post0              pypi_0    pypi
python-dotenv             1.0.1                    pypi_0    pypi
python-multipart          0.0.9                    pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
referencing               0.35.1                   pypi_0    pypi
regex                     2024.4.28                pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
rich                      13.7.1                   pypi_0    pypi
rpds-py                   0.18.0                   pypi_0    pypi
ruff                      0.4.3                    pypi_0    pypi
s3transfer                0.10.1                   pypi_0    pypi
safetensors               0.4.3                    pypi_0    pypi
scipy                     1.13.0                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
setuptools                68.2.2                   pypi_0    pypi
shellingham               1.5.4                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
starlette                 0.37.2                   pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tensorboard               2.16.2                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.19.1                   pypi_0    pypi
tomlkit                   0.12.0                   pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
torch                     2.1.0+cu118              pypi_0    pypi
torchaudio                2.1.0+cu118              pypi_0    pypi
torchdiffeq               0.2.3                    pypi_0    pypi
torchvision               0.16.0+cu118             pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
transformers              4.40.1                   pypi_0    pypi
triton                    2.1.0                    pypi_0    pypi
typer                     0.12.3                   pypi_0    pypi
typing-extensions         4.9.0                    pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
ujson                     5.9.0                    pypi_0    pypi
urllib3                   2.2.1                    pypi_0    pypi
uvicorn                   0.29.0                   pypi_0    pypi
uvloop                    0.19.0                   pypi_0    pypi
watchfiles                0.21.0                   pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
werkzeug                  3.0.2                    pypi_0    pypi
wheel                     0.43.0                   pypi_0    pypi
xz                        5.4.6                h5eee18b_1  
zipp                      3.18.1                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1  
`

@PommesPeter

**Comment by BruceLeeeee** [comment]
`Traceback (most recent call last):
  File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/train.py", line 753, in <module>
    main(args)
  File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/train.py", line 514, in main
    loss_dict = transport.training_losses(model, x_mb, model_kwargs)
  File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/transport/transport.py", line 148, in training_losses
    model_output = model(xt, t, **model_kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 839, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/models/model.py", line 751, in forward
    x = layer(
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 839, in forward
    output = self._fsdp_wrapped_module(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/models/model.py", line 555, in forward
    modulate(self.ffn_norm(x), shift_mlp, scale_mlp),
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/models/components.py", line 53, in forward
    output = self._norm(x.float()).type_as(x)
  File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/models/components.py", line 40, in _norm
    return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + self.eps)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB. GPU 0 has a total capacty of 79.35 GiB of which 32.19 MiB is free. Process 30630 has 79.31 GiB memory in use. Of the allocated memory 76.58 GiB is allocated by PyTorch, and 848.92 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`
torch                     2.1.0+cu118 
transformers              4.40.1
diffusers                 0.27.2 
flash-attn                2.3.1.post1
accelerate                0.30.0

@PommesPeter

**Comment by PommesPeter** [comment]
@BruceLeeeee we use `precision: bf16` and `grad_precision: fp32`, you can try these hyper-parameters, and we will check the `model.py` code whether is correct.

**Comment by PommesPeter** [comment]
> > Traceback (most recent call last):
> > File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/train.py", line 753, in 
> > main(args)
> > File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/train.py", line 514, in main
> > loss_dict = transport.training_losses(model, x_mb, model_kwargs)
> > File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/transport/transport.py", line 148, in training_losses
> > model_output = model(xt, t, **model_kwargs)
> > File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
> > return self._call_impl(*args, **kwargs)
> > File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
> > return forward_call(*args, **kwargs)
> > File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 839, in forward
> > output = self._fsdp_wrapped_module(*args, **kwargs)
> > File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
> > return self._call_impl(*args, **kwargs)
> > File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
> > return forward_call(*args, **kwargs)
> > File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/models/model.py", line 751, in forward
> > x = layer(
> > File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
> > return self._call_impl(*args, **kwargs)
> > File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
> > return forward_call(*args, **kwargs)
> > File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 839, in forward
> > output = self._fsdp_wrapped_module(*args, **kwargs)
> > File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
> > return self._call_impl(*args, **kwargs)
> > File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
> > return forward_call(*args, **kwargs)
> > File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/models/model.py", line 555, in forward
> > modulate(self.ffn_norm(x), shift_mlp, scale_mlp),
> > File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
> > return self._call_impl(*args, **kwargs)
> > File "/opt/conda/envs/Lumina_T2X/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
> > return forward_call(*args, **kwargs)
> > File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/models/components.py", line 53, in forward
> > output = self._norm(x.float()).type_as(x)
> > File "/mnt/new_sfs_turbo/lsh2/train_projects/Lumina-T2X/lumina_t2i/models/components.py", line 40, in _norm
> > return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + self.eps)
> > torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB. GPU 0 has a total capacty of 79.35 GiB of which 32.19 MiB is free. Process 30630 has 79.31 GiB memory in use. Of the allocated memory 76.58 GiB is allocated by PyTorch, and 848.92 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> 
> > Training arguments: {
> > "results_dir": "checkpoints_Lumina-T2I/train_run_0",
> > "model": "DiT_Llama_5B_patch2",
> > "image_size": 1024,
> > "max_steps": 1000000,
> > "global_batch_size": 1,
> > "micro_batch_size": 1,
> > "global_seed": 0,
> > "vae": "sdxl",
> > "num_workers": 2,
> > "log_every": 1000,
> > "ckpt_every": 1000,
> > "master_port": 8964,
> > "model_parallel_size": 1,
> > "data_parallel": "fsdp",
> > "precision": "fp16",
> > "grad_precision": "fp16",
> > "local_diffusers_model_root": "sdxl-vae-fp16-fix",
> > "lr": 0.0001,
> > "auto_resume": true,
> > "resume": null,
> > "init_from": "Lumina-T2I",
> > "grad_clip": 2.0,
> > "wd": 0.0,
> > "qk_norm": true,
> > "tokenizer_path": "Llama-2-7b-hf",
> > "lm": "Llama-2-7b-hf",
> > "caption_dropout_prob": 0.1,
> > "max_text_tokens": 128,
> > "rope_scaling_factor": 1.0,
> > "snr_type": "uniform",
> > "max_seq_len": 4224  (unused)
> > }
> 
> torch 2.1.0+cu118 transformers 4.40.1 diffusers 0.27.2 flash-attn 2.3.1.post1 accelerate 0.30.0
> 
> @PommesPeter

we will reproduce the problem with your environment setting.

**Comment by BruceLeeeee** [comment]
Hi, @PommesPeter 
Can you provide the training arguments of DiT_Llama_5B_patch2 checkpoint?

**Comment by BruceLeeeee** [comment]
> training用的是FSDP，会shard paraemter /gradient，所以GPU memory会随着GPU变多，变少。
> 单卡A100跑不起来

FSDP need mulit-gpu training to reduce GPU memory (DiT_Llama_5B_patch2)
