### ISSUE TITLE
Any plan for developing a diffusers version?

### ISSUE THREAD

**Issue by JincanDeng** [Alpha-VLLM/Lumina-T2X#13]
Thanks for your great work! Do you have any plan for developing a diffusers version of the infer pipeline?

**Comment by gaopengpjlab** [comment]
Thanks for your advice. Lumina is still under actively development. We will release a diffuser version once we reach a stable version.

**Comment by JincanDeng** [comment]
> Thanks for your advice. Lumina is still under actively development. We will release a diffuser version once we reach a stable version.

Looking forward to it!

**Comment by PommesPeter** [comment]
Hi @JincanDeng ,
We have supported Lumina-Next in the diffusers, check the instructions at [here](https://github.com/Alpha-VLLM/Lumina-T2X/blob/main/README.md#fast-demo)
