### ISSUE TITLE
Can you tell me the compute requirements for inference and training?

### ISSUE THREAD

**Issue by ninjasaid2k** [Alpha-VLLM/Lumina-T2X#14]

**Comment by PommesPeter** [comment]
Hi, @ninjasaid2k

Thank you for your questioning. you can read our technical report for getting more information about training requirements.

Lumina-T2X technical report: https://arxiv.org/pdf/2405.05945
related information:
![image](https://github.com/Alpha-VLLM/Lumina-T2X/assets/54879512/8325089a-2bfc-4ca1-8566-4b6beef1a304)

Moreover, we use 1 A800 GPU for inference.

**Comment by TruthSearcher** [comment]
> Moreover, we use 1 A800 GPU for inference.

What is the minimum memory usage required and what is the speed you can expect for a generation compared to PixArt-a

**Comment by PommesPeter** [comment]
> > Moreover, we use 1 A800 GPU for inference.
> 
> What is the minimum memory usage required and what is the speed you can expect for a generation compared to PixArt-a

The lumina-T2I 5B model will cost about 49GB memory usage for inference with 0.4s per step. we will release a more lightweight model for faster inference and lower memory usage after fully testing our lightweight version of the model. The demo can be used at [demo](http://106.14.2.150:10021/)
