### ISSUE TITLE
What dataset was used to train the video generation model?

### ISSUE THREAD

**Issue by Dibbidy** [Alpha-VLLM/Lumina-T2X#15]
What dataset was used to train the video generation model? I noticed that you have mentioned that you've used a 14M dataset for the image model but I'm not sure what the video model was trained on.

**Comment by gaopengpjlab** [comment]
We train independently upon pexel, webvid and pandahd. Pexel and webvid dataset supports scene generation. PandaHD is good at generating human motion.
