### ISSUE TITLE
about alignment evaluation or prompt following study?

### ISSUE THREAD

**Issue by BruceLeeeee** [Alpha-VLLM/Lumina-T2X#16]
Hi, thanks for the amazing work.
I have read your technical report about T2I part, but no found about alignment evaluation or prompt following study.

**Comment by gaopengpjlab** [comment]
Thanks for your suggestion. We will add more T2I evaluation soon.

**Comment by BruceLeeeee** [comment]
And I noticed your model also supports other languages (e.g. Chinese), although the image looks a little worse. I'd like to know if you used other languages text-image pairs in training?

**Comment by gaopengpjlab** [comment]
The prompts contain only English. However, after english-only training, the Lumina-T2X model developed emerging multilingual capabilities, including the ability to understand and generate Chinese, emoji, Japanese, and other languages.

**Comment by gaopengpjlab** [comment]
We will include the discuss of emerging multi-lingual ability into our report in the future.

**Comment by BruceLeeeee** [comment]
amazing! 
it seems no discussion of multilingual capabilities when using large language models as text encoders in current research.

Looking forward to training script support (doesn't work properly right now)

**Comment by gaopengpjlab** [comment]
We will update the training script soon.
