### ISSUE TITLE
Distributed package doesn't have NCCL built in

### ISSUE THREAD

**Issue by Bigfield77** [Alpha-VLLM/Lumina-T2X#17]
Hello,

On windows, I have to change line 88 of demo.py to use "gloo" instead of NCCL

I guess this only impacts training?

sincerely

**Comment by PommesPeter** [comment]
Hi, @Bigfield77

We currently support inference on Linux, and we are not fully testing the functionality on Windows. We will initially process the group with NCCL both training and inference. Please stay tuned.

**Comment by Bigfield77** [comment]
thanks for the answer!
