### ISSUE TITLE
Questions about next line / next frame token

### ISSUE THREAD

**Issue by yjhong89** [Alpha-VLLM/Lumina-T2X#24]
Hi. Thanks for sharing great work!

- In case of video generation, how next line / next frame token attached to latent frames ??
  <img width="624" alt="image" src="https://github.com/Alpha-VLLM/Lumina-T2X/assets/26890721/871eb4b8-8ac5-4432-a59a-a9f251909c31">

  - It seems like next line token attached to every end of height, and next frame token attached to the very end of one latent frame. Is this right?
  - Since videos have different resolution and duration, how this thing managed in one batch of different videos ? Is there learnable PAD tokens attached to make same length inside a batch?

- Do you have any plan to release training code (especially T2V) and dataset ??

Thank you!

**Comment by yjhong89** [comment]
Additionally, what rules attaching theses tokens ?
- From Figure 2 right
<img width="341" alt="image" src="https://github.com/Alpha-VLLM/Lumina-T2X/assets/26890721/20610654-7f55-4111-8b17-a10e3bd1a9c6">

**Comment by gaopengpjlab** [comment]
Lumina T2V trains on open-source dataset including PandaHD, Webvid and Pexel. Please download from their own homepage.

**Comment by siyang1992** [comment]
> Lumina T2V trains on open-source dataset including PandaHD, Webvid and Pexel. Please download from their own homepage.

Thanks for your wonderful work. I want to know where is the code of next line / next frame token attached to latent frames. From the codebase, I can not find them.

**Comment by Frankluox** [comment]
> > Lumina T2V trains on open-source dataset including PandaHD, Webvid and Pexel. Please download from their own homepage.
> 
> Thanks for your wonderful work. I want to know where is the code of next line / next frame token attached to latent frames. From the codebase, I can not find them.

The nextline token is self.eol_token in lumina_t2i/models/model.py

**Comment by yjhong89** [comment]
@Frankluox , thanks. Maybe next_frame token will be seen in t2v models.py
