### ISSUE TITLE
Showcase lumina-t2x on Huggingface Spaces with get free GPU grant(A100s)

### ISSUE THREAD

**Issue by yvrjsharma** [Alpha-VLLM/Lumina-T2X#28]
Congratulations on your amazing project and the successful [live gradio demo](http://106.14.2.150:10022/)! It would also be great to have the demo available on [Huggingface Spaces](https://huggingface.co/spaces). This could help with more community engagement and drive more visibility to the project. We at Huggingface also provide free GPU grants through the **ZeroGPU** program, which includes free A100s. We would be happy to extend the grant to your application.

Here are some useful links to help you get started on Spaces:
- A step-by-step guide to building Gradio apps on Spaces: https://huggingface.co/docs/hub/en/spaces-sdks-gradio
- Zero GPU Org: https://huggingface.co/zero-gpu-explorers

Please let us know if you need any further assistance or support in integrating your project with Spaces or any other relevant Huggingface offerings.

**Comment by PommesPeter** [comment]
Hi @yvrjsharma,

We have encountered a problem. Our code depends on flash-attn, which requires GPU compilation and installation. May we request GPU access now?

**Comment by yvrjsharma** [comment]
Hi @PommesPeter sure, please go ahead.

**Comment by PommesPeter** [comment]
link here: https://huggingface.co/spaces/Alpha-VLLM/Lumina-Next-T2I

**Comment by yvrjsharma** [comment]
Sure thing! To raise a request for a community grant, please head over to the settings tab of your Space and submit a request there. Additionally, I recommend making your demo compatible with ZeroGPU. You can find more information on this at the ZeroGPU organization, which you can access through this link: https://huggingface.co/zero-gpu-explorers. You'd also need to join this ZeroGPU Org, so please raise a request to join, and let me know your HF username and I can approve your request.

**Comment by PommesPeter** [comment]
okay, I have updated the code to be compatible with ZeroGPU. But I can't find the 'request to join org' button.
![image](https://github.com/Alpha-VLLM/Lumina-T2X/assets/54879512/75c9aab6-1462-4108-9c7f-4868352826bc)

**Comment by PommesPeter** [comment]
my huggingface username is `PommesPeter`

**Comment by yvrjsharma** [comment]
Ah, sorry about that. I've added your HF username to the org. You should be able to assign a ZeroGPU yourself now. Let me know if there are any other blockers 🤗

**Comment by PommesPeter** [comment]
okay, i will go ahead.

**Comment by PommesPeter** [comment]
I try to create a new space in ZeROGPU org, but i get this error.
![image](https://github.com/Alpha-VLLM/Lumina-T2X/assets/54879512/d04b51a2-ae5d-4aca-9174-e4ca59820300)

**Comment by PommesPeter** [comment]
i have solved it.

**Comment by yvrjsharma** [comment]
umm, Are you not able to assign a ZeroGPU to your Space ?

**Comment by PommesPeter** [comment]
I just recreated an HF Space repo in our org and was able to assign a ZeroGPU.

**Comment by yvrjsharma** [comment]
Perfect, congratulations! Can you share the link with me please?

**Comment by yvrjsharma** [comment]
Great! If you have any further issues, please feel free to tag me (@ysharma) in a Spaces discussion.
