### ISSUE TITLE
Hi , when T2A model? also T2Music? best regards

### ISSUE THREAD

**Issue by researcher48** [Alpha-VLLM/Lumina-T2X#45]

**Comment by gaopengpjlab** [comment]
To be released soon.

**Comment by PommesPeter** [comment]
Hi @researcher48 ,
we have released lumina text-to-music and lumina text-to-audio code in the repo. check this out https://github.com/Alpha-VLLM/Lumina-T2X/tree/main/lumina_audio and https://github.com/Alpha-VLLM/Lumina-T2X/tree/main/lumina_music
