### ISSUE TITLE
Question about lognorm

### ISSUE THREAD

**Issue by jiashenggu** [Alpha-VLLM/Lumina-T2X#57]
Hi, great work! The paper mentions lognorm, but I couldn't find the implementation. Could you let me know if it's used in the code? If so, please tell me where I can find it. Thank you very much!

**Comment by zhuole1025** [comment]
Thanks for your interest! The lognorm schedule is used in our ImageNet models. You can find the implementation here:
https://github.com/Alpha-VLLM/Lumina-T2X/blob/04bb30bde5c2a1d2516251f6b9b92ad69bed2534/Next-DiT-ImageNet/transport/transport.py#L111

**Comment by jiashenggu** [comment]
> Thanks for your interest! The lognorm schedule is used in our ImageNet models. You can find the implementation here:
> https://github.com/Alpha-VLLM/Lumina-T2X/blob/04bb30bde5c2a1d2516251f6b9b92ad69bed2534/Next-DiT-ImageNet/transport/transport.py#L111

Thank you for your response! I'm curious why you only use it in ImageNet.

**Comment by zhuole1025** [comment]
That's because we tested the lognorm schedule only at the very beginning of our T2I project and found no significant improvements. However, it is worth paying more attention to the schedule for training large-scale flow and diffusion models.
