### ISSUE TITLE
ComfyUI support

### ISSUE THREAD

**Issue by edwinzeng2005** [Alpha-VLLM/Lumina-T2X#58]
Are you planning to add support for ComfyUI?

**Comment by gaopengpjlab** [comment]
Lumina is still under active development . Once finished, we will import lumina into ComfyUI and Diffuser.

**Comment by edwinzeng2005** [comment]
Thanks for the clarification!
And hopefully, we won't need to spend an hour to compile flash-attn as well. I am not sure if it can be precompiled.
