### ISSUE TITLE
Why doesn't inference time increase with pixel area?

### ISSUE THREAD

**Issue by jiashenggu** [Alpha-VLLM/Lumina-T2X#65]
When I generate 1024x1024 images on one A800, inference time is 15s/image
However, when I generate 1664x1664 images, inference time is 55s/image

**Comment by zhuole1025** [comment]
I am not sure about your question. The inference time increases with the growth of resolution due to the squared complexity in attention blocks. However, we adopt Flash Attention to speed up inference.

**Comment by jiashenggu** [comment]
> I am not sure about your question. The inference time increases with the growth of resolution due to the squared complexity in attention blocks. However, we adopt Flash Attention to speed up inference.

Sorry for the typo, when I generate 1664x1664 images, inference time is **55**s/image. I think the inference time should be ~39s, (~2.6x)

**Comment by gaopengpjlab** [comment]
the time costs of attention is quadratic with respect to sequence length.

**Comment by jiashenggu** [comment]
> the time cost of attention is quadratic with respect to sequence length.  

I understand. However, the inference time for the Lumina T2I increases at a rate faster than quadratic. When I increase the sequence length to 1.5 times, I expect the time cost to be ~2.6 times higher, but in reality, the time cost increases by ~3.6 times.

**Comment by ChrisLiu6** [comment]
> > the time cost of attention is quadratic with respect to sequence length.
> 
> I understand. However, the inference time for the Lumina T2I increases at a rate faster than quadratic. When I increase the sequence length to 1.5 times, I expect the time cost to be ~2.6 times higher, but in reality, the time cost increases by ~3.6 times.

When increasing resolution from 1024 -> 1664, the area is 2 times larger rather than 1.5 times,  and so is the number of patches.

**Comment by jiashenggu** [comment]
> > > the time cost of attention is quadratic with respect to sequence length.
> > 
> > 
> > I understand. However, the inference time for the Lumina T2I increases at a rate faster than quadratic. When I increase the sequence length to 1.5 times, I expect the time cost to be ~2.6 times higher, but in reality, the time cost increases by ~3.6 times.
> 
> When increasing resolution from 1024 -> 1664, the area is 2 times larger rather than 1.5 times, and so is the number of patches.

Man, I said "I expect the time cost to be **~2.6** times", I know how to calculate area. The problem is the increase is greater than **2.6**.

**Comment by ChrisLiu6** [comment]
Sorry, how do you work out the number 2.6? Is that an approximation of 1.5*1.5?

I mean, when increasing resolution from 1024 -> 1664, the sequence length grows to 2 times (rather than 1.5 times that you mentioned in your reply). Then due to the quadratic complexity of attention, the time cost can be up to 4 times of the original.

**Comment by jiashenggu** [comment]
> I mean, when increasing resolution from 1024 -> 1664, the **sequence length** already grows to 2.6 times (rather than 1.625) because you need to consider the area rather than the edge. Then due to the quadratic complexity of attention, the time cost can be up to 2.6^2≈7 times of the original.

Thank you for your response! I finally get it. It is different from unet, its inference time is $n^4$.
