### ISSUE TITLE
Any plans integrating to diffusers?

### ISSUE THREAD

**Issue by Luciennnnnnn** [Alpha-VLLM/Lumina-T2X#69]
Hi, is there any plans to integrate lumina into diffusers? which would greatly improve usability for many users.

**Comment by haofanwang** [comment]
Looking forward to diffusers integration!

**Comment by PommesPeter** [comment]
we are working in process on supporting diffusers, please stay tuned.

**Comment by PommesPeter** [comment]
Hi @haofanwang ,
We have supported Lumina-Next in the diffusers, check the instruction at [here](https://github.com/Alpha-VLLM/Lumina-T2X/blob/main/README.md#fast-demo)
