### ISSUE TITLE
great work 

### ISSUE THREAD

**Issue by liubo0902** [Alpha-VLLM/Lumina-T2X#7]
this is a great work for t2x. can you update the checkpoint url of the t2i, since the old url is invalid

**Comment by PommesPeter** [comment]
Thank you for your interest in lumina-t2x, we will soon put up the address of the latest huggingface model!

**Comment by PommesPeter** [comment]
> this is a great work for t2x. can you update the checkpoint url of the t2i, since the old url is invalid

Thank you for your interest in lumina-t2x, we will soon put up the address of the latest huggingface model!

**Comment by PommesPeter** [comment]
Hi liubo,

we uploaded our final model for lumina-t2i, here is the link: https://huggingface.co/Alpha-VLLM/Lumina-T2I @liubo0902
