### ISSUE TITLE
Are Lumina-T2Audio and Lumina-T2Music the same?

### ISSUE THREAD

**Issue by researcher48** [Alpha-VLLM/Lumina-T2X#77]

**Comment by gaopengpjlab** [comment]
Almost the same but with trivial difference. Please check the details included in our paper. 

https://github.com/Alpha-VLLM/Lumina-T2X/blob/main/assets/lumina-next.pdf

Lumina-Audio code and demo shall be released within one day.

**Comment by PommesPeter** [comment]
Hi @researcher48 ,
we have released lumina text-to-music and lumina text-to-audio code in the repo. check this out https://github.com/Alpha-VLLM/Lumina-T2X/tree/main/lumina_audio and https://github.com/Alpha-VLLM/Lumina-T2X/tree/main/lumina_music

**Comment by ninjasaid2k** [comment]
> Hi @researcher48 , we have released lumina text-to-music and lumina text-to-audio code in the repo. check this out https://github.com/Alpha-VLLM/Lumina-T2X/tree/main/lumina_audio and https://github.com/Alpha-VLLM/Lumina-T2X/tree/main/lumina_music

and just to be sure 
This: is referring to music:
>[2024-06-07] We have released the Lumina-T2Music (Text-to-Music) code and model for music generation. [MODEL](https://huggingface.co/Alpha-VLLM/Lumina-T2Music) [DEMO](http://139.196.83.164:8000/)

whereas: 
> [2024-06-19] We have released the Lumina-T2Music (Text-to-Music) code and model for music generation. [MODEL](https://huggingface.co/Alpha-VLLM/Lumina-T2Music)

is supposed to say T2Audio?

**Comment by PommesPeter** [comment]
yes, it is supposed to say T2Audio. sorry for my typo on this news.
