### ISSUE TITLE
How is captioning labeled for Lumina-T2I models?

### ISSUE THREAD

**Issue by nunbuzor** [Alpha-VLLM/Lumina-T2X#85]

**Comment by gaopengpjlab** [comment]
We use mixture-of-captioner to label images.

**Comment by TruthSearcher** [comment]
> We use mixture-of-captioner to label images.

do you use an LLM to caption images?

**Comment by TruthSearcher** [comment]
> We use mixture-of-captioner to label images.

do you use an VLM to caption images for natural language prompts for T2I?
