### ISSUE TITLE
Error when downloading LuminaModel

### ISSUE THREAD

**Issue by ninjasaid2k** [Alpha-VLLM/Lumina-T2X#88]
Error occured when downloading Lumina Model.

> Error occurred when executing DownloadAndLoadLuminaModel:
> 
> No such file or directory: "C:\\Users\\ninja\\Downloads\\StableSwarmUI\\dlbackend\\comfy\\ComfyUI\\models\\lumina\\Lumina-Next-SFT\\consolidated.00-of-01.safetensors"
> 
> File "C:\Users\ninja\Downloads\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 151, in recursive_execute
> output_data, output_ui = get_output_data(obj, input_data_all)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\ninja\Downloads\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 81, in get_output_data
> return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\ninja\Downloads\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 74, in map_node_over_list
> results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\ninja\Downloads\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-LuminaWrapper\nodes.py", line 80, in loadmodel
> sd = load_torch_file(os.path.join(model_path, "consolidated.00-of-01.safetensors"))
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\ninja\Downloads\StableSwarmUI\dlbackend\comfy\ComfyUI\comfy\utils.py", line 14, in load_torch_file
> sd = safetensors.torch.load_file(ckpt, device=device.type)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "C:\Users\ninja\Downloads\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\safetensors\torch.py", line 311, in load_file
> with safe_open(filename, framework="pt", device=device) as f:
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by PommesPeter** [comment]
Hi @ninjasaid2k 

It appears that the Lumina model download failed. Please ensure that you can access huggingface.co.
