### ISSUE TITLE
Lumina Next img2img

### ISSUE THREAD

**Issue by thelemuet** [Alpha-VLLM/Lumina-T2X#91]
Hello! I have been playing with the SFT model and I'm really impressed to far!

Are there any plans to implement img2img for your image models? For regular img2img usage like SD but also I get the feeling this model would work really well for upscaling/refining since it's already able to generate very consistent/coherent images at higher resolutions (unlike ie: SDXL at higher than 1024x1024).

**Comment by gaopengpjlab** [comment]
Can you suggest any popular image2image model? I will take a look at it. By the way, in lumina-t2x technique report, we illustrate that training-free image2image editing is possible.

**Comment by kijai** [comment]
I'm also very interested in img2img and curious how the showcased image editing was achieved? I have tried the basics of using encoded image instead of random noise/augmented with noise, but that doesn't seem to work. Or did you use reverse sampling?

**Comment by thelemuet** [comment]
> Can you suggest any popular image2image model? I will take a look at it. By the way, in lumina-t2x technique report, we illustrate that training-free image2image editing is possible.

I believe all Stable Diffusion model can do img2img (have not tried SD3 but I assume it does).

Here is a quick example usage using SDXL. Starting from a simple image of a 3d render where I know want to keep the composition, lighting and colors. I would set it to generate 30 steps but skip a few steps depending on how much I want to retain from the original image and how much new details I want the model to generate. Here is what it looks like from original image and different results depending on starting step:

![iti1](https://github.com/Alpha-VLLM/Lumina-T2X/assets/86247933/c68451a1-fd0b-41ac-937f-7259d152f2ff)


And an upscale example:

![upscale1](https://github.com/Alpha-VLLM/Lumina-T2X/assets/86247933/59042dbd-d537-4baf-b74e-b4ea377da990)

**Comment by gaopengpjlab** [comment]
We will release a demo similar as stablediffusionimg2image pipeline. 

https://huggingface.co/docs/diffusers/en/api/pipelines/stable_diffusion/img2img

**Comment by zhuole1025** [comment]
> I'm also very interested in img2img and curious how the showcased image editing was achieved? I have tried the basics of using encoded image instead of random noise/augmented with noise, but that doesn't seem to work. Or did you use reverse sampling?

Our implementation is identical to this in the diffusers, but you have to be cautious with the start timestep which is affected by the time-shifting scale. Welcome to add this into ComfyUI and have some tests!

**Comment by kijai** [comment]
> > I'm also very interested in img2img and curious how the showcased image editing was achieved? I have tried the basics of using encoded image instead of random noise/augmented with noise, but that doesn't seem to work. Or did you use reverse sampling?
> 
> Our implementation is identical to this in the diffusers, but you have to be cautious with the start timestep which is affected by the time-shifting scale. Welcome to add this into ComfyUI and have some tests!

Got it. Thank you! 
![image](https://github.com/Alpha-VLLM/Lumina-T2X/assets/40791699/233ded8f-a6e7-4c53-98fe-e465af025829)
