### ISSUE TITLE
lumina_next_t2i: _pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by Fashizel** [Alpha-VLLM/Lumina-T2X#93]
Hey all!
Followed the instructions religiously but when I run lumina_next_t2i with:

`
 command = [
        "python", "-u", "/root/lumina_next_t2i/sample.py",
        "--ckpt", "/root/lumina_next_t2i/Lumina-Next-SFT",
        "--image_save_path", "/root/output",
        "--num_sampling_steps", "80",
        "--caption_path", "prompt.txt",
        "--seed", "0",
        "--resolution", "512",
        "--time_shifting_factor", "0.1",
        "--batch_size", "1"
        ]
        subprocess.run(command)
`

I get : 

`
Traceback (most recent call last):
  File "/root/lumina_next_t2i/sample.py", line 341, in <module>
    main(args, 0, master_port)
  File "/root/lumina_next_t2i/sample.py", line 99, in main
    train_args = torch.load(os.path.join(args.ckpt, "model_args.pth"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, 'v'.
`

Not sure what could be the case, thanks!

**Comment by zhuole1025** [comment]
We recommend you to use the sampling [scripts](https://github.com/Alpha-VLLM/Lumina-T2X/blob/main/lumina_next_t2i_mini/scripts/sample.sh) in the `lumina-next-t2i-mini` folder.

**Comment by Fashizel** [comment]
> We recommend you to use the sampling [scripts](https://github.com/Alpha-VLLM/Lumina-T2X/blob/main/lumina_next_t2i_mini/scripts/sample.sh) in the `lumina-next-t2i-mini` folder.

Sure, but I dont think thats the issue. I am able to run the script, the error is on trying to load the checkpoint.

**Comment by zhuole1025** [comment]
Does your checkpoint end with '.safetensor'?

**Comment by PommesPeter** [comment]
it looks like you have not download the full files in huggingface repo. please check your folder if it's contains `model_args.pth`
